# This is a basic workflow to help you get started with Actions

name: Auto Deployment


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ["dev", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup NodeJS in our environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script to install dependencies
        run: |
          yarn install
          CI='' yarn run build
        env:
          CI: false


      # Syncs your 'build' folder from buildng the Vue app with an S3 bucket
      - name: AWS S3 Sync with build folder
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: 'build'

      # Clears the CloudFront cache so new requests will receive the latest version of your app
      - name: Invalidate Cloudfront to clear cache
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}